---
# handlers file for lb

- name: restart haproxy
  service: 
    name: haproxy
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart keepalived
  service:
    name: keepalived
    daemon_reload: yes
    state: restarted
    enabled: yes
